language: scala
scala:
- 2.11.6
- 2.10.5
jdk:
- openjdk6
notifications:
  email:
    recipients:
    - lance.gatlin@s-mach.net
script:
- sbt ++$TRAVIS_SCALA_VERSION coverage test coverageReport -sbt-version 0.13.5 -J-Xms4G -J-Xmx4G
after_success:
- sbt coveralls codacyCoverage -sbt-version 0.13.5
- >
      test "${TRAVIS_PULL_REQUEST}" = 'false' &&
      test "${TRAVIS_BRANCH}" == 'master' &&
      test "${TRAVIS_JDK_VERSION}" = 'openjdk6' &&
      sbt 'set credentials += Credentials("Sonatype Nexus Repository Manager", "oss.sonatype.org", System.getenv("SONATYPE_USER"), System.getenv("SONATYPE_PASS"))' publish
