language: scala
scala:
- 2.11.1
jdk:
- openjdk6
notifications:
  email:
    recipients:
    - lance.gatlin@s-mach.net
script:
- sbt scoverage:test -J-Xms4G -J-Xmx4G
- sbt coveralls -J-Xms4G -J-Xmx4G
env:
  global:
  - secure: C+EY+X0B5fFH25LWscULBniDcbcvXdTFBEsEzuWNhHXnref+At23tC71cO5TGFYfAKKudF8ah2QWmSw3SSvdggnOLKnAmHXdzJHgMUsGxeja2ivB4NtCSLc172LTGiHBLnYKWamWSfcuPoRJp1zfpy+S+vrLE4vGwXnUpqUF83M=
  - secure: jeLwg5fID5dolKe1sNXY3J9dbYOeHD9avf9dS41vzbXOR76iyl0KYQEdeZ/8ILuKDbTlYySAeEj2+5JCgzd0q2P+xXtuVArxBlrBtnoQCdpNXCiKu8+jxP+/IlZp0baS2y3lviap8mdDBuJyJtEIub93jTklF01KDlmd9dC0Y/Y=
  - secure: h23RYLu03ARMkFzNih+R80p7s8NLFjo8ei/52MCclUN2OU5Pz4TAPlL3DxgCdlbNCmfgGzUZqf2wksCZ1sy7K0yPUOfhw6d54DXHaznrR4b2xPNxT3RfKE952OcxF127d+/AlZ0ufWevn1PQHXLIrFJsUjTe797HuIHjEmjuWlc=
after_success:
  - >
      test "${TRAVIS_PULL_REQUEST}" = 'false' &&
      test "${TRAVIS_BRANCH}" == 'master' &&
      test "${TRAVIS_JDK_VERSION}" = 'openjdk6' &&
      sbt 'set credentials += Credentials("Sonatype Nexus Repository Manager", "oss.sonatype.org", System.getenv("SONATYPE_USER"), System.getenv("SONATYPE_PASS"))' publish
